config/routes.rb
Courses::Application.routes.draw do

  match 'test' => "Messaging#test"

  root :to => 'Home#index', :as => :welcome

  
  match 'login/student' => 'home#student', :as => :student_login
  match 'login/teacher' => 'home#teacher', :as => :teacher_login

  resources :users do
    resources :notify_pref
  end

  match 'auth/:provider/:callback' => 'Sessions#create'
  match 'auth/failure' => "Sessions#fail"

  match 'courses/save_sections' => 'CoursesDisplay#save_sections', :as => :save_sections
  match 'courses/remove_section/:section_id' => 'CoursesDisplay#remove_section', :as => :remove_section
  match 'courses/add_section/:section_id' => 'CoursesDisplay#add_section', :as => :add_section
  match 'courses/:major/:course' => 'CoursesDisplay#section', :as => :showSections
  match 'courses/:major' => 'CoursesDisplay#course', :as => :showCourses
  match 'courses/' => 'CoursesDisplay#index', :as => :courses

  match 'student/' => "Student#index", :as => :student_index
	
  match 'teacher/' => "Teacher#index", :as => :teacher_index

  match 'messaging' => "Messaging#index"
  resources :announce

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
#  symbolize :type, :in => [:Homework, :Quiz, :Exam, :General], :scopes => true

  def self.types
    [:Homework, :Quiz, :Exam, :General]
  end

  belongs_to :courses
  belongs_to :sections

  validates :title, :presence => true
  validates :atype, :presence => true
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
 belongs_to :user
 validates :uid, :uniqueness => true
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :major
  has_many :sections
  has_many :announcements
  has_and_belongs_to_many :users
end

app/models/major.rb
class Major < ActiveRecord::Base
	validates :subjectCode, :uniqueness => true
	has_many :courses
end

app/models/notify_pref.rb
class NotifyPref < ActiveRecord::Base
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => true
  belongs_to :user
  has_many :responses

  def answer
    Response.where(:question_id => self.id, :is_answer => true)
  end

  def answer=(new_ans)
    raise 'Answer doesn\'t have an ID' unless new_ans.id

    # check new_ans exists in db
    raise "Answer #{new_ans.id} doesn't exist in db" unless Response.find(new_ans.id)
    new_ans.is_answer = true
    new_ans.question_id = self.id
    new_ans.save
    new_ans
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  has_one :question
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :users
  has_many :announcements
end

app/models/user.rb
class User < ActiveRecord::Base

  def courses_form_data
    courses = []
    sections.each do |section|
      course = Course.find(section.course_id)
      course_name = course.subjectCode + " " + course.courseNumber.to_s
      unless courses.include?([course_name, section.course_id])
        courses << [course_name, section.course_id]
      end
    end
    return courses
  end

  #TODO add deletion of relation/mapping from users_sections when a user is destroyed
  has_and_belongs_to_many :sections
  has_and_belongs_to_many :courses

  has_many :authorizations, :dependent => :destroy

  has_one :notify_pref, :dependent => :destroy
  accepts_nested_attributes_for :notify_pref
  validates_presence_of :notify_pref
end

app/controllers/courses_display_controller.rb
=begin
  This controller is responsible for displaying the course selection
  scene as well as powering the add/remove section functions for the session
=end  
class CoursesDisplayController < ApplicationController

layout "coursesdisplay"

# Retrieves the current users sections
  def users_sections
    unless session[:mySections]
      session[:mySections] = []
    end
    session[:mySections]
  end

  def add_section
    @mySections = users_sections
    @mySections << params[:section_id].to_i
    respond_to {|format| format.js}
    flash['notice'] = "Section " + params[:section_id] + " Added!"
    #redirect_to '/courses/'
  end
  
  def remove_section
    @mySections = users_sections
    if( params[:section_id].to_i == @mySections.delete(params[:section_id].to_i))
        flash['notice'] = "Section "+ params[:section_id] + " removed!"
    end
    logger.debug "MySections: #{session[:mySections]}"
    respond_to do |format|
      format.js
    end
  end
  
	def course
		@major = Major.find(:first, :conditions => {:subjectCode => params[:major]})
		respond_to do |format|
	    format.js
	  end
	end

	def section
		@major = Major.find(:first, :conditions => {:subjectCode => params[:major]})
		@course = @major.courses.find(:first, :conditions => {:courseNumber => params[:course]})
		respond_to do |format|
		  format.js
        end
	end

    def save_sections
      # make sure the users sections are clear
      current_user.sections = []
      current_user.courses = []

      courses = []
      session[:mySections].each do |section|
        currentSection = Section.find(section)
        current_user.sections << currentSection 
        unless courses.include?(currentSection.course_id)
          current_user.courses << Course.find(currentSection.course_id)
          courses << currentSection.course_id
        end
      end
      if session[:isStudent]
        redirect_to student_index_path
      else
        redirect_to teacher_index_path
      end
    end
	
	def index
		@majors = Major.all
        unless session[:mySections]
          session[:mySections] = []
          current_user.sections.each do |section|
            session[:mySections] << section.id.to_i
          end
        end
        @mySections = session[:mySections]
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_filter :authenticate

def index
end

def teacher
  logger.debug "Teacher!\n"
  session['isStudent'] = false
  redirect_to "/auth/google"
end

def student
  logger.debug "student\n"
  session['isStudent'] = true
  redirect_to "/auth/google"
end

end

app/helpers/announce_helper.rb
module AnnounceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_display_helper.rb
module CoursesDisplayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messaging_helper.rb
module MessagingHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/notify_prefs_helper.rb
module NotifyPrefsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses_display/_course.html.erb
<% count = 0 %>
<% @major.courses.each do |course| %>
    <li class="
    <% if (count % 2 == 0) %> 
        odd
    <% else %>
        even
    <% end %>
    ">
		<a href="<%=  showSections_path(@major.subjectCode, course.courseNumber.to_s) %>" data-remote="true">
			
            <div id="left"><div class="title"><%= course.courseNumber %></div></div>
			<div class="subtext"><%= course.title %></div></a>
	</li>
	<% count += 1 %>
<% end %>

app/views/courses_display/_majors.html.erb
<ul>
<% count = 0 %>
<% majors.each do |major| %>
	<li class="
	<% if (count % 2 == 0) %> 
		odd
	<% else %>
		even
	<% end %>
	">
		<a href="<%= showCourses_path(major.subjectCode) %>" data-remote="true">
			<div id="left"><div class="title"><%= major.subjectCode %></div></div>
			<div class="subtext"><%= major.subjectDescription %></div></a>
	</li>
	<% count += 1 %>
<% end %>
</ul>

app/views/courses_display/_myCourses.html.erb
		<% if @mySections %>
			<% @mySections.each do |section| %>
				<li>
					<% course = Course.find(Section.find(section).course_id) %>
					<%= link_to '-', remove_section_path(section), :remote => true, :id => "remove" %>
                    <span class="course"><%= course.subjectCode %><%= course.courseNumber %></span>
					<span class="section"><%= Section.find(section).sectionId %></span>
				</li>
			<% end %>
		<% end%>

app/views/courses_display/_section.html.erb
<% @course.sections.each do |section| %>

<div id="section-header">
	<a href="<%= add_section_path(section.id) %>" data-remote="true" id="add">+</a>
	<span class="left"><strong>Section: </strong><%= section.sectionId %></span>
	<span class="right"><strong>CRN: </strong><%= section.referenceNumber %></span>
</div>

<ul>
	<% if(section.days ) %>
	<li>Days: <%= section.days %></li>
	<% end %>
	<li>
		<% if not (section.startTime.to_i == section.endTime.to_i) %>
		Time: <%= section.startTime.strftime("%l:%M %p") %> - <%= section.endTime.strftime("%l:%M %p") %>
		<% end %>
	</li>
	<li>
		Type: <%= section.type %>
	</li>
	<li>
		Building: <%= section.building %>
	</li>
	<li>
		Instructor: <%= section.instructor %>
	</li>
	<li>
		<% if section.room != 0 %>
		Room: <%= section.room %>
		<% end %>
	</li>
</ul>	
<% end %>

app/views/courses_display/index.html.erb
<%= flash['notice'] %>
<div id="wrapper">
	<div id="header">
		<h1 class="afs-charis-sil">Hey there 
        <% if current_user %>
          <%= current_user.firstname %>.
        <% end %>
        </h1>
		<h2 class="afs-pt-sans">Let's add your classes.</h2>
	</div>
	<div id="courseSelectionContent" class="afs-pt-sans">
		<div id="major-col"><%= render :partial => "majors", :object => @majors %></div>
		<div id="course-col">select a major</div>
		<div id="section-col">select a course</div>
	</div>
	<div id="myCourses" class="afs-pt-sans">
		<ul>
			<div id="myCourses-header" >Your Sections</div>
			<div id="myCourses-content" ><%= render :partial => "myCourses" %></div>
		</ul>
        <%= link_to "Save Sections", save_sections_path %>
	</div>
</div>