config/routes.rb
Courses::Application.routes.draw do

  match 'test' => "Messaging#test"

  root :to => 'Home#index', :as => :welcome

  
  match 'login/student' => 'home#student', :as => :student_login
  match 'login/teacher' => 'home#teacher', :as => :teacher_login

  resources :users do
    resources :notify_pref
  end

  match 'auth/:provider/:callback' => 'Sessions#create'
  match 'auth/failure' => "Sessions#fail"

  match 'courses/save_sections' => 'CoursesDisplay#save_sections', :as => :save_sections
  match 'courses/remove_section/:section_id' => 'CoursesDisplay#remove_section', :as => :remove_section
  match 'courses/add_section/:section_id' => 'CoursesDisplay#add_section', :as => :add_section
  match 'courses/:major/:course' => 'CoursesDisplay#section', :as => :showSections
  match 'courses/:major' => 'CoursesDisplay#course', :as => :showCourses
  match 'courses/' => 'CoursesDisplay#index', :as => :courses

  match 'student/' => "Student#index", :as => :student_index
	
  match 'teacher/' => "Teacher#index", :as => :teacher_index

  match 'messaging' => "Messaging#index"
  resources :announce

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
#  symbolize :type, :in => [:Homework, :Quiz, :Exam, :General], :scopes => true

  def self.types
    [:Homework, :Quiz, :Exam, :General]
  end

  belongs_to :courses
  belongs_to :sections

  validates :title, :presence => true
  validates :atype, :presence => true
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
 belongs_to :user
 validates :uid, :uniqueness => true
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :major
  has_many :sections
  has_many :announcements
  has_and_belongs_to_many :users
end

app/models/major.rb
class Major < ActiveRecord::Base
	validates :subjectCode, :uniqueness => true
	has_many :courses
end

app/models/notify_pref.rb
class NotifyPref < ActiveRecord::Base
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => true
  belongs_to :user
  has_many :responses

  def answer
    Response.where(:question_id => self.id, :is_answer => true)
  end

  def answer=(new_ans)
    raise 'Answer doesn\'t have an ID' unless new_ans.id

    # check new_ans exists in db
    raise "Answer #{new_ans.id} doesn't exist in db" unless Response.find(new_ans.id)
    new_ans.is_answer = true
    new_ans.question_id = self.id
    new_ans.save
    new_ans
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  has_one :question
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :users
  has_many :announcements
end

app/models/user.rb
class User < ActiveRecord::Base

  def courses_form_data
    courses = []
    sections.each do |section|
      course = Course.find(section.course_id)
      course_name = course.subjectCode + " " + course.courseNumber.to_s
      unless courses.include?([course_name, section.course_id])
        courses << [course_name, section.course_id]
      end
    end
    return courses
  end

  #TODO add deletion of relation/mapping from users_sections when a user is destroyed
  has_and_belongs_to_many :sections
  has_and_belongs_to_many :courses

  has_many :authorizations, :dependent => :destroy

  has_one :notify_pref, :dependent => :destroy
  accepts_nested_attributes_for :notify_pref
  validates_presence_of :notify_pref
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_filter :authenticate

def index
end

def teacher
  logger.debug "Teacher!\n"
  session['isStudent'] = false
  redirect_to "/auth/google"
end

def student
  logger.debug "student\n"
  session['isStudent'] = true
  redirect_to "/auth/google"
end

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_filter :isStudent

  def isStudent
    unless current_user.isStudent
      redirect_to "/"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
#    @user = User.find(params[:id])
	@user = current_user

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/announce_helper.rb
module AnnounceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messaging_helper.rb
module MessagingHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/notify_prefs_helper.rb
module NotifyPrefsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Courses</h1><br/>

<h1>Teachers</h1>
<%= link_to "", teacher_login_path, :id=>"google-sso" %>

<h1>Students</h1>
<%= link_to "", student_login_path, :id=>"google-sso" %>

app/views/student/index.html.haml
#wrapper
	#header
		%ul#nav
			%li
				%a{:href => '#' , :class => 'active'} Dashboard
			%li 
				= link_to "Courses", courses_path
		%input{:type => 'text', :name => 'searchbar', :value => 'Search'}

		%ul#user-info
			%li= link_to current_user.firstname, current_user
			%li
				%a{:href => '#' } Settings

	#header2
		#left.column
			#header
				%ul#nav
					%li
						%a{:href => "#"} Checklist
		#middle.column
			#header
				%ul#nav
					%li
						%a{:href => "#"} Messages
		#right.column
			#header
				%ul#nav
					%li
						%a{:href => "#"} Questions
	#content
		#left.column2
			#header2
				#header
					%ul#nav
						%li
							%a{:href => "#"} Calendar
		#right.column2
			%h1
				%a{:href => "#"} News Feed
			%ul.tabbar
				%li.activetab ALL
				- current_user.courses.each do |course|
					%li.inactivetab= course.subjectCode + " " + course.courseNumber.to_s
			#news-feed
				%ul
					%li
					- current_user.courses.each do |course|
						- course.announcements.each do |announcement|
							%li
								#news-post 
									#news-header
										%h1= course.subjectCode + " " + course.courseNumber.to_s
										%h2= announcement.title
										#span.dueDate= announcement.dueDate
									%p= announcement.description
									#news-details
										%span.datePosted= announcement.created_at
										%span.atype= announcement.atype
										%a{:href => "#", :class => "ask"} Ask a question
						
	#footer